version: "3"

services:
  app:
    build: .
    tty: true
    volumes:
      - .:/app
    ports:
      - 4567:4567
    environment: 
      BUNDLE_APP_CONFIG: /app/.bundle # https://blog.freedom-man.com/ruby-docker-bundler
    env_file: 
      - ./apikey.env
    command: "bundle exec rackup config.ru -o 0.0.0.0 -p 4567"
